CREATE TABLE SREDNJA_SKOLA (
  ID_Ucenik INTEGER NOT NULL,
  Ime_ucenika TEXT NOT NULL,
  Prezime_ucenika TEXT NOT NULL,
  Datum_rodjenja_ucenika TEXT NOT NULL CHECK (Datum_rodjenja_ucenika GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  OIB TEXT NOT NULL CHECK (length(OIB) = 11 AND OIB GLOB '[0-9]*'),
  Ime_oca TEXT NOT NULL,
  Adresa_ucenika TEXT NOT NULL,
  Broj_razreda INTEGER NOT NULL,
  Slovo_razreda TEXT NOT NULL,
  Naziv_skole TEXT NOT NULL,
  Adresa_skole TEXT NOT NULL,
  Postanski_broj INTEGER NOT NULL,
  Mjesto TEXT NOT NULL,
  Naziv_zupanije TEXT NOT NULL,
  Naziv_predmeta TEXT NOT NULL,
  Broj_sati_tjedno INTEGER NOT NULL CHECK (Broj_sati_tjedno > 0),
  Ime_nastavnika TEXT NOT NULL,
  Prezime_nastavnika TEXT NOT NULL,
  Datum_rodjenja_nastavnika TEXT NOT NULL CHECK (Datum_rodjenja_nastavnika GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  Pocetak_rada TEXT NOT NULL CHECK (Pocetak_rada GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  Kraj_rada TEXT NULL,
  Naziv_zvanja_nastavnika TEXT NOT NULL,
  Ocjena INTEGER NOT NULL CHECK (Ocjena BETWEEN 1 AND 5)
);