DELETE FROM ZAVRŠNA_O WHERE UČENICI_ID_Učenik IN (SELECT ID_Učenik FROM UČENICI WHERE RAZREDI_ID_Razred = 1);
DELETE FROM P_UČENIK WHERE UČENICI_ID_Učenik IN (SELECT ID_Učenik FROM UČENICI WHERE RAZREDI_ID_Razred = 1);
DELETE FROM UČENICI WHERE RAZREDI_ID_Razred = 1;
DELETE FROM N_RAZRED WHERE RAZREDI_ID_Razred = 1;
DELETE FROM RAZREDI WHERE ID_Razred = 1;

DELETE FROM UCENIK_PREGLED WHERE Broj_razreda = 4 AND Slovo_razreda = 'C';