DELETE FROM ZAVRSNA_O WHERE UCENICI_ID_Ucenik IN (SELECT ID_Ucenik FROM UCENICI WHERE RAZREDI_ID_Razred = 1);
DELETE FROM P_UČENIK WHERE UCENICI_ID_Ucenik IN (SELECT ID_Ucenik FROM UCENICI WHERE RAZREDI_ID_Razred = 1);
DELETE FROM UCENICI WHERE RAZREDI_ID_Razred = 1;
DELETE FROM N_RAZRED WHERE RAZREDI_ID_Razred = 1;
DELETE FROM RAZREDI WHERE ID_Razred = 1;

DELETE FROM UCENIK_PREGLED WHERE Broj_razreda = 4 AND Slovo_razreda = 'C';